name: Pyodide Build
on: [workflow_dispatch]
jobs:
  Pyodide-Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libjpeg-dev zlib1g-dev libtiff-dev libfreetype-dev liblcms2-dev libwebp-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.2
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.14
      - run: pip install pyodide-build==0.21.0
      - run: pyodide build
